- name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@34d5f75b0d6d0d22f06d83acf2fa1b144409ec83
  uses: docker/login-action@v1.4.1
  with:
    # Server address of Docker registry. If not set then will default to Docker Hub
    registry: # optional
    # Username used to log against the Docker registry
    username: # optional
    # Password or personal access token used to log against the Docker registry
    password: 
    # Log out from the Docker registry at the end of a job
    logout: # optional, default is true
